Iter18
PerfectStepCoder/shorturl pull request #17
Opened 2024-10-22 17:26 UTC by PerfectStepCoder

2024-10-29 03:24 UTC, vokinneberg requested changes
Поздравляю с первым ревью седьмого спринта! 🎉 Этот спринт даёт возможность немного отдохнуть от написания кода и при этом попробовать на практике интересные инструменты.⚡ Ты сделал улучшения своего приложения, и оно проходит автотесты — молодец! 👍 Тем не менее, по традиции хочу сделать несколько предложений и комментариев относительно твоего кода. 🤓

**Сильные стороны твоего PR:**

1. Твой код проходит автотесты. 👍
2. Код отформатирован с использованием `gofmt` и `goimport`.
3. Ты реализовал примеры и бенчмарки. 💪
4. Ты получил профиль приложения и сделал улучшения производительности.
5. Ты улучшил покрытие приложения тестами.
6. Ты добавил описание в файл [[README.md](http://readme.md/)](http://README.md).

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. Было бы здорово добавить автоматическое вычисление покрытия в CI pipeline при помощи github actions. Можно так же добавить badge, который будет показывать процент покрытия тестами проекта, в README файл. Как это сделать можно посмотреть вот здесь, например https://github.com/vladopajic/go-test-coverage
2. Общее покрытие тестами сейчас 16%, хотя по условию задачи требуется не менее 40%.
3. В примерах строка `Test` меняется на `Example`, иначе пример не будет отображаться в документации.
4. Стоит поработать над обработкой ошибок.
5. Было бы здорово сделать запуск профилирования настраиваемым, добавив отдельный флаг конфигурации.
6. Поскольку большая часть спринта была посвящена паттернам, было бы здорово, если бы ты применил какой-нибудь из них в своём приложении.

2024-10-29 03:24 UTC, vokinneberg commented on cmd/shortener/example_test.go
> +func ExampleTestShorterURL() {
В примерах строка `Test` меняется на `Example`, иначе пример не будет отображаться в документации.
```suggestion
func ExampleShorterURL() {
```

2024-10-29 03:24 UTC, vokinneberg commented on README.md
> +> go run ./cmd/shortener/main.go -a 0.0.0.0:9999 -b http://localhost:9999
👍 За добавление описания!

2024-10-29 03:24 UTC, vokinneberg commented on cmd/shortener/main.go
> +	routes.Mount("/debug/pprof/", http.DefaultServeMux)
Стоит сделать запуск профилирования настраиваемым, добавив отдельный флаг конфигурации.

2024-10-29 03:24 UTC, vokinneberg commented on cmd/shortener/main.go
> +	close(inputCh)
👍

2024-10-29 03:24 UTC, vokinneberg commented on cmd/shortener/main_test.go
> +func Example() {
Стоит вынести пример  в файл `example_test.go` и назвать пример в соответствии, что он демонстрирует.   
```suggestion
func ExampleSave() {
```

2024-10-29 03:24 UTC, vokinneberg commented on internal/handlers/base.go
> +		}
Стоит проверить ошибку и вернуть пользователю сообщение об ошибке, в противном случае получается, что ошибка игнорируется.

```suggestion
		if err != nil {
		    http.Error(res, "Error", http.StatusInternalServerError)
		}
	        for _, url := range allURLs {
		        outputURLs = append(outputURLs, models.ResponseURL{
			        OriginalURL: url.OriginalURL, ShortURL: fmt.Sprintf("%s/%s", baseURL, url.ShortHash),
		        })
	        }
```

2024-10-29 03:24 UTC, vokinneberg commented on internal/handlers/base.go
> +		defer func() {
Уже кажется упоминал, что нет смысла принудительно закрывать `req.Body`  так как фреймворк это сделает автоматически.

2024-10-29 03:24 UTC, vokinneberg commented on internal/handlers/base.go
> +			log.Printf("Error parsing JSON: %s", err)
Если нам не удалось смаршаллить данные, мы точно хотим продолжать?

2024-10-29 03:24 UTC, vokinneberg commented on internal/handlers/middlewares.go
> +	}
Стоит инвертировать проверку.
```suggestion
	if err == nil {
	    return "", false
	}
        // Кука существует и проходит проверку, продолжаем выполнение следующего обработчика
        logrus.Printf("Existing valid user ID: %s", userUID)
        return userUID, true
```

2024-10-29 03:24 UTC, vokinneberg commented on internal/handlers/middlewares.go
> +		h.ServeHTTP(w, r)
Стоит сразу сделать проверку ошибки. Это более наглядно и позволяет сделать обработку ошибок более читаемой.
```suggestion
	if err != nil {
	    h.ServeHTTP(w, r)
	}
	
	// Проверка и декодирование куки
	userUID, isValid := ValidateUserUID(cookie.Value)
	if isValid {
		// Кука существует и проходит проверку, продолжаем выполнение следующего обработчика
		logrus.Printf("Existing valid user ID: %s", userUID)
		h.ServeHTTP(w, r)
		return
	} else {
		logrus.Printf("Wrong UserUID: %s", cookie.Value)
		w.WriteHeader(http.StatusUnauthorized)
		return
	}

	h.ServeHTTP(w, r)
```

2024-10-29 03:24 UTC, vokinneberg commented on internal/handlers/middlewares.go
> +		}
Так же не стоит использовать `if-else`.
```suggestion
		if err != nil {
		    if r.Method == http.MethodGet && r.URL.Path == "/api/user/urls" {
				    encodedUserUID := r.Header.Get("Authorization")
				    var validErr bool
				    userUID, validErr := ValidateUserUID(encodedUserUID)
				    if validErr {
					    ctx := context.WithValue(r.Context(), UserKeyUID, userUID)
					    h.ServeHTTP(w, r.WithContext(ctx))
				    } else {
					    logrus.Printf("Wrong UserUID: %s", encodedUserUID)
					    w.WriteHeader(http.StatusUnauthorized)
					    return
				    }
			    } else { // Создаем пользователю uid (методы POST DELETE PUT)
				    userUID, err := SetNewCookie(w)
				    if err == nil {
					    ctx := context.WithValue(r.Context(), UserKeyUID, userUID)
					    h.ServeHTTP(w, r.WithContext(ctx))
				    }
			    }
		}
		
	        // Проверка и декодирование куки
	        userUID, isValid := ValidateUserUID(cookie.Value)
	        if isValid {
		        // Кука существует и проходит проверку, продолжаем выполнение следующего обработчика
		        logrus.Printf("Existing valid user ID: %s", userUID)
		        ctx := context.WithValue(r.Context(), UserKeyUID, userUID)
		        h.ServeHTTP(w, r.WithContext(ctx))
	        } else {
		        logrus.Printf("Wrong UserUID: %s", cookie.Value)
		        w.WriteHeader(http.StatusUnauthorized)
		        return
	        }
```

2024-10-29 03:24 UTC, vokinneberg commented on internal/storage/database.go
> +	// ; CREATE INDEX idx_user_uid ON urls (user_uid);
Стоит разобраться почему.

2024-10-29 03:24 UTC, vokinneberg commented on internal/storage/database.go
> +	defer urls.Close()
`defer` стоит перенести на строку 168, где мы только получаем `urls`. Это идеоматический подход, в противном случае `defer` не очень то и нужен.

2024-10-29 03:24 UTC, vokinneberg commented on internal/storage/database.go
> +	_ = s.poolConnectionToDB.SendBatch(context.Background(), batch)
Все правильно, не стоит игнорировать ошибку!

2024-10-29 03:24 UTC, vokinneberg commented on internal/tests/storageInmemory_test.go
> +func generateUUID() (string, error) {
А для чего нам самим реализовывать генерацию UUID? Почему нельзя воспользоваться готовой реализацией?

2024-10-29 06:34 UTC, PerfectStepCoder commented on internal/storage/database.go
> +	defer urls.Close()
Готово, поправил

2024-10-29 06:39 UTC, PerfectStepCoder commented on internal/handlers/base.go
> +		defer func() {
Убрал лишний вызов функции

2024-10-29 06:39 UTC, PerfectStepCoder commented on cmd/shortener/main_test.go
> +func Example() {
Готово, перенес

2024-10-29 07:27 UTC, PerfectStepCoder commented on internal/handlers/base.go
> +			log.Printf("Error parsing JSON: %s", err)
Добавил в обработчик возврат ошибки пользователю, статус BadRequest

2024-10-29 07:31 UTC, PerfectStepCoder commented on cmd/shortener/main.go
> +	routes.Mount("/debug/pprof/", http.DefaultServeMux)
Готово, добавил новый флаг -p   - значит добавить route c профилированием

2024-10-29 07:37 UTC, PerfectStepCoder commented on internal/tests/storageInmemory_test.go
> +func generateUUID() (string, error) {
Заменил на встроенный генератор UUID

2024-10-29 07:43 UTC, PerfectStepCoder commented on internal/storage/database.go
> +	_ = s.poolConnectionToDB.SendBatch(context.Background(), batch)
Добавил обработку исключения при выполнении команд а батче

2024-11-02 22:06 UTC, vokinneberg approved these changes
Поздравляю с успешным ревью седьмого спринта! 🎉 Текущее покрытие тестами действительно считается, как 34.8%. Попробуй посмотреть в html версии отчета, что именно не покрыто `go tool cover -html=profile.cov`.

2024-11-08 07:53 UTC, merged