Iter20
PerfectStepCoder/shorturl pull request #19
Opened 2024-11-04 20:30 UTC by PerfectStepCoder

2024-11-08 05:55 UTC, vokinneberg requested changes
Поздравляю с первым ревью седьмого спринта! 🎉 Ты сделал улучшения своего приложения 👍 Тем не менее, по традиции хочу сделать несколько предложений и комментариев относительно твоего кода. 🤓

**Сильные стороны твоего PR:**

1. Ты реализовал статически анализатор 👍
2. Ты добавил новые флаги в приложение.

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

- Ты не слил ветку `iter18`  в main, поэтому к сожалению я вижу изменения с прошлой итерации.
- Не стоит оставлять "магические числа" в коде, стоит реализовать его как именованную константу.
- Мне кажется метод `main`  разросся и можно было бы вынести некоторые его части в отдельные функции. Это поможет повысить читаемость кода.
- Я бы рекомендовал группировать экспортируемые и не экспортируемые функции в файле, например экспортируемые в первой половине файла, а не экспортируемые во второй.
- По условию задачи необходимо добавить "*не менее одного анализатора остальных классов пакета [staticcheck.io](http://staticcheck.io/)*".
- Auth middleware. Очень запутанный код хэндлера, сложно разобраться в том, что происходит. Я попытался его немного упростить. Так же несколько советов по поводу того, чего стоит избегать, если возможно:
    - Стоит избегать использования `if/else`, если без этого можно обойтись
    - Не стоит делать проверок `err == nil`, если возможно. Стоит проверить, что ошибка `err != nil` и сразу вернуть управление.
    - Не стоит хардкодить маршруты в коде middleware, если это происходит то проблема очевидно в дизайне приложения. Какие маршруты обрабатываются middleware, стоит устанавливать при настройке роутера.
- Покрытие кода тестами меньше 55%.

2024-11-08 05:55 UTC, vokinneberg commented on cmd/shortener/main.go
> +var buildCommit = "N/A"  // коммит сборки
Можно объединить объявление переменных.

```suggestion
var (
	buildVersion = "N/A" // версия продукта
	buildDate    = "N/A" // дата сборки
	buildCommit  = "N/A" // коммит сборки
)
```

2024-11-08 05:55 UTC, vokinneberg commented on cmd/shortener/main.go
> +	inputCh := make(chan []string, 10000) // TODO вынести 10000 в переменные окружения
Все правильно, не стоит оставлять "магические числа" в коде, стоит реализовать его как именованую константу.
```suggestion
	inputCh := make(chan []string, 10000) // TODO вынести 10000 в переменные окружения
```

2024-11-08 05:55 UTC, vokinneberg commented on cmd/shortener/main.go
> +	fmt.Printf("Build version: %s\n", buildVersion)
Мне кажется метод `main`  разросся и можно было бы вынести некоторые его части в отдельные функции. Это поможет повысить читаемость кода.

2024-11-08 05:55 UTC, vokinneberg commented on cmd/shortener/main_test.go
> +func findInCookie(resp *resty.Response) (string, bool) { // userUUID, bool
Я бы рекомендовал группировать экспортируемые и не экспортируемые функции в файле, например экспортируемые в первой половине файла, а не экспортируемые во второй.

2024-11-08 05:55 UTC, vokinneberg commented on cmd/staticlint/main.go
> +		if pass.Pkg.Name() != "main" {
👍

2024-11-08 05:55 UTC, vokinneberg commented on cmd/staticlint/main.go
> +	for _, v := range staticcheck.Analyzers {
По условию задачи необходимо добавить "_не менее одного анализатора остальных классов пакета staticcheck.io_".

2024-11-08 05:55 UTC, vokinneberg commented on internal/handlers/base.go
> +		batchSize := 15                                            // указываем размер батча TOTO перенести в переменные окружения
 Так же рекомендую вынести в именованные константы.

2024-11-08 05:55 UTC, vokinneberg commented on internal/handlers/base.go
> +			http.Error(res, "Bad JSON data", http.StatusBadRequest)
Если произошла ошибка, видимо стоит вернуть управление из хендлера?

2024-11-08 05:55 UTC, vokinneberg commented on internal/handlers/middlewares.go
> +var (
 Стоит перенести определение глобальных переменных (и констант) в начало файла, после импортов.

2024-11-08 05:55 UTC, vokinneberg commented on internal/handlers/middlewares.go
> +}
Очень запутанный код хэндлера, сложно разобраться в том, что происходит. Я попытался его немного упростить. Так же несколько советов по поводу того, чего стоит избегать, если возможно:

- Стоит избегать использования `if/else`, если без этого можно обойтись
- Не стоит делать проверок `err == nil`, если возможно. Стоит проверить, что ошибка `err != nil` и сразу вернуть управление.
- Не стоит хардкодить маршруты в коде middleware, если это происходит то проблема очевидно в дизайне приложения. Какие маршруты обрабатываются middleware, стоит устанавливать при настройке роутера.

```suggestion
// Auth для подписанной куки с идентификатором пользователя.
func Auth(h http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		// Попытка получить куку
		cookie, err := r.Cookie("userUID")

		if err != nil {
			// Проверка метода и пути для GET запроса
			if !errors.Is(err, http.ErrNoCookie) {
				logrus.Error("Error getting cookie:", err)
				w.WriteHeader(http.StatusInternalServerError)
				return
			}

			// Если нет куки
			if r.Method == http.MethodGet {
				encodedUserUID := r.Header.Get("Authorization")
				userUID, valid := ValidateUserUID(encodedUserUID)
				if !valid {
					logrus.Printf("Wrong UserUID: %s", encodedUserUID)
					w.WriteHeader(http.StatusUnauthorized)
					return
				}
				ctx := context.WithValue(r.Context(), UserKeyUID, userUID)
				h.ServeHTTP(w, r.WithContext(ctx))
				return
			}

			// Создаем пользователю uid (методы POST DELETE PUT)
			userUID, err := SetNewCookie(w)
			if err != nil {
				logrus.Error("Error setting new cookie:", err)
				w.WriteHeader(http.StatusInternalServerError)
				return
			}
			ctx := context.WithValue(r.Context(), UserKeyUID, userUID)
			h.ServeHTTP(w, r.WithContext(ctx))
			return
		}

		// Проверка и декодирование куки
		userUID, valid := ValidateUserUID(cookie.Value)
		if !valid {
			logrus.Printf("Wrong UserUID: %s", cookie.Value)
			w.WriteHeader(http.StatusUnauthorized)
			return
		}

		// Кука существует и проходит проверку, продолжаем выполнение следующего обработчика
		logrus.Printf("Existing valid user ID: %s", userUID)
		ctx := context.WithValue(r.Context(), UserKeyUID, userUID)
		h.ServeHTTP(w, r.WithContext(ctx))
	}
}
```

2024-11-08 05:55 UTC, vokinneberg commented on internal/handlers/objects.go
> +		cookies, err := req.Cookie("userUID")
Стоит добавить проверку `ErrNoCookie`.

2024-11-08 05:55 UTC, vokinneberg commented on internal/storage/database.go
> +	}
Меня смущает бесконечный цикл. Возможно стоит все-таки указать условие выхода?
```suggestion
	for i := 0; i < len(shortsHashURL); i++ {
		_, err := batchResults.Exec()
		if err != nil {
			log.Printf("Error executing batch command: %v", err)
			return err
		}
	}
```

2024-11-08 05:55 UTC, vokinneberg commented on internal/storage/inmemory_test.go
> +func TestCreateURL(t *testing.T) {
Мне кажется тут можно было бы использовать табличные тесты.

2024-11-08 07:59 UTC, PerfectStepCoder commented on cmd/shortener/main.go
> +var buildCommit = "N/A"  // коммит сборки
Готово, изменил

2024-11-08 08:02 UTC, PerfectStepCoder commented on cmd/shortener/main.go
> +	inputCh := make(chan []string, 10000) // TODO вынести 10000 в переменные окружения
Готово, поправил

2024-11-08 08:25 UTC, PerfectStepCoder commented on cmd/shortener/main.go
> +	fmt.Printf("Build version: %s\n", buildVersion)
Выполнил рефакторинг

2024-11-08 08:27 UTC, PerfectStepCoder commented on cmd/shortener/main_test.go
> +func findInCookie(resp *resty.Response) (string, bool) { // userUUID, bool
Готово, поправил

2024-11-08 08:31 UTC, PerfectStepCoder commented on internal/handlers/base.go
> +		batchSize := 15                                            // указываем размер батча TOTO перенести в переменные окружения
Перенес в константы

2024-11-08 08:33 UTC, PerfectStepCoder commented on internal/handlers/base.go
> +			http.Error(res, "Bad JSON data", http.StatusBadRequest)
Готово, поправил

2024-11-08 08:35 UTC, PerfectStepCoder commented on internal/handlers/middlewares.go
> +var (
Готово, поправил

2024-11-08 09:33 UTC, PerfectStepCoder commented on internal/handlers/objects.go
> +		cookies, err := req.Cookie("userUID")
Готово, поправил

2024-11-08 09:37 UTC, PerfectStepCoder commented on internal/storage/database.go
> +	}
Готово, поправил

2024-11-12 03:08 UTC, vokinneberg commented on cmd/shortener/main.go
> +	inputCh := make(chan []string, 10000) // TODO вынести 10000 в переменные окружения
По-моему еще одно место осталось.

2024-11-12 03:10 UTC, vokinneberg approved these changes
Поздравляю с успешным ревью восьмого спринта! 🎉

2024-11-12 07:15 UTC, merged