Iter5
PerfectStepCoder/shorturl pull request #5
Opened 2024-07-09 09:16 UTC by PerfectStepCoder

2024-07-15 21:02 UTC, vokinneberg requested changes
Поздравляю с завершением Первого Спринта и первым ревью! 🤗 Твой покрыт тестами, работает и проходит тесты. Отличная работа! 🚀

**Сильные стороны твоего PR:**

1. **Функциональность:** Код функционален и корректен! 🚀
2. **Структура сервиса:** По условию задания структура сервиса должна представлять собой набор пакетов и структур, разделённых на слои. Твой код неплохо структурирован и разбит на отдельные компоненты и пакеты. 👍
3. **Тестирование:** Реализованы тесты базовых сценариев. 👍

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. **Использование интерфейсов:** Было бы здорово если бы ты реализовал в твоём коде  интерфейсы хранения, что позволяет отделить конкретную реализацию от кода, который использует интерфейс. 👍
2. **Синхронизация доступа** к хранилищу. На будущее -стоит подумать, как будет себя вести код при конкурентной обработкенескольких запросов на сервере и как можно синхронизировать доступ кхранилищу.
3. **Комментарии:** Было бы здорово, если бы ты добавил комментарии в коде там, где есть сложные места, которые требуют пояснения, а также для публичных методов.
4. **Форматирование:** Было бы здорово отформатировать файлы проекта.

2024-07-15 21:02 UTC, vokinneberg commented on cmd/client/main.go
> +func main() {
По коду клиента я бы рекомендовал разделить его на несколько логических блоков, которые можно отделить пробелами — довольно сложно воспринимать непрерывную "простыню" кода.

Также я бы не рекомендовал злоупотреблять "очевидными" комментариями. В общем случае, комментарии используются либо для разделения блоков кода, либо для пояснения неочевидных мест. При разделении блоков кода, если возникает желание добавить комментарий, стоит задуматься о переносе блока в отдельную функцию с информативным именем.

2024-07-15 21:02 UTC, vokinneberg commented on cmd/client/main.go
> +    endpoint := "http://localhost:8080/"
Можно вынести endpoint и content-type за пределы метода main и объявить, как константы.

2024-07-15 21:02 UTC, vokinneberg commented on cmd/client/main.go
> +        panic(err)
Не стоит использовать панику, так как она приводит к крашу приложения. Рекомендую вызвать `log.Fatalf(...)`, которая выведет сообщение об ошибке и завершит процесс при помощи вызова `os.Exit(1)`.

2024-07-15 21:02 UTC, vokinneberg commented on cmd/shortener/main.go
> +    routes.Get("/{id}", handlers.GetURL(inMemoryStorage))
Тут стоит отформатировать код, это можно сделать при помощи `go fmt`.

2024-07-15 21:02 UTC, vokinneberg commented on cmd/shortener/main.go
> +		panic(err)
Не стоит использовать панику, так как она приводит к крашу приложения. Рекомендую вызвать `log.Fatalf(...)`, которая выведет сообщение об ошибке и завершит процесс при помощи вызова `os.Exit(1)`.

2024-07-15 21:02 UTC, vokinneberg commented on cmd/shortener/config/flags.go
> +    if envRunAddr := os.Getenv("SERVER_ADDRESS"); envRunAddr != "" {
Стоит добавить префикс к переменным окружения во избежание конфликта с другими переменными окружения `SERVER_ADDRESS` -> `SHORTENER_SERVER_ADDRESS`.

2024-07-15 21:02 UTC, vokinneberg commented on cmd/shortener/config/flags.go
> +func splitHostPort(addr string) (string, int, error) {
Можно попробовать использовать пакет `net/url` для парсинга URL.

2024-07-15 21:02 UTC, vokinneberg commented on cmd/shortener/config/flags.go
> +func ParseFlags() Settings {
Тут можно использовать указатель `*Settings` во избежание лишнего копирвоания.  
```suggestion
func ParseFlags() *Settings {
```

2024-07-15 21:02 UTC, vokinneberg commented on cmd/shortener/config/config.go
> +	if a.Host == "" && a.Port == 0 {
Этот код похож на реализованный в  `splitHostPort(...)`. Возможно тут тоже стоит попробовать использовать пакет `net/url` для парсинга URL?

2024-07-15 21:02 UTC, vokinneberg commented on internal/README.md
> +# internal/app
Нужен ли нам этот файл в проекте?

2024-07-15 21:02 UTC, vokinneberg commented on internal/storage/inmemory.go
> +func NewStorage(maxLength int) *Storage {
Мне кажется, тут название переменной не совсем точно описывает ее смысл. `maxLength` звучит так что эта переменная устанавливает максимальную длину (размер) хранилища, а она устанавливает длину короткой ссылки.

2024-07-15 21:02 UTC, vokinneberg commented on internal/storage/inmemory.go
> +	data map[string]string
Предлагаю на будущее подумать о том, как будет работать `Storage` в условиях многочисленных одновременных запросов, причем когда на чтение запросов приходит кратно больше? Стоит добавить синхронизацию?

2024-07-15 21:02 UTC, vokinneberg commented on internal/handlers/base.go
> +		originURLbytes, _ := io.ReadAll(req.Body)
Не стоит забывать закрывать тело ответа после чтения.
 
```suggestion
		originURLbytes, _ := io.ReadAll(req.Body)
		defer func() {
                      if err := res.Body.Close(); err != nil {
                          log.Errorf("could not close response body: %v", err)
                      }
                  }()
```

2024-07-15 21:02 UTC, vokinneberg commented on cmd/shortener/main_test.go
> +            assert.Equal(t, tc.expectedCode, resp.StatusCode(), "Код ответа не совпадает с ожидаемым")
В общем-то в использовании сторонних assert  библиотек нет ничего неправильного, но разработчики Go не рекоменду использовать сторонние assert библиотеки, так как _это либо останавливает тест раньше времени (если вызовы используют `t.Fatalf` или `panic`), либо упускает интересную информацию о том, что тест сделал правильно. Это также заставляет assert библиотеку создавать совершенно новый подъязык вместо использования существующего языка программирования (самого Go)._ https://go.dev/wiki/TestComments

2024-07-15 21:02 UTC, vokinneberg commented on cmd/shortener/main_test.go
> +            assert.Equal(t, tc.expectedCode, resp.StatusCode(), "Код ответа не совпадает с ожидаемым")
👍 за информативное сообщение для ассерта.

2024-07-17 04:25 UTC, PerfectStepCoder commented on cmd/client/main.go
> +func main() {
Готово, выполнил рефакторинг и протестил клиента на работу

2024-07-17 04:25 UTC, PerfectStepCoder commented on cmd/client/main.go
> +    endpoint := "http://localhost:8080/"
Поправил

2024-07-17 04:25 UTC, PerfectStepCoder commented on cmd/client/main.go
> +        panic(err)
Заменил на log.Fatalf

2024-07-17 04:26 UTC, PerfectStepCoder commented on cmd/shortener/main.go
> +    routes.Get("/{id}", handlers.GetURL(inMemoryStorage))
Все файлы проекта обработал командой: gofmt -s -w .

2024-07-17 04:26 UTC, PerfectStepCoder commented on cmd/shortener/main.go
> +		panic(err)
Поправил

2024-07-17 04:26 UTC, PerfectStepCoder commented on internal/storage/inmemory.go
> +func NewStorage(maxLength int) *Storage {
Переименовал

2024-07-17 04:27 UTC, PerfectStepCoder commented on internal/handlers/base.go
> +		originURLbytes, _ := io.ReadAll(req.Body)
Поправил

2024-07-17 04:27 UTC, PerfectStepCoder commented on cmd/shortener/main_test.go
> +            assert.Equal(t, tc.expectedCode, resp.StatusCode(), "Код ответа не совпадает с ожидаемым")
Поправил

2024-07-17 05:40 UTC, PerfectStepCoder commented on internal/storage/inmemory.go
> +	data map[string]string
Добавил объект для синхронизации

2024-07-19 21:24 UTC, vokinneberg approved these changes
Привет 👋, вижу ты реализовал улучшения по моим комментариям и мне кажется код стал более структурированный, его стало легче читать. Здорово! 👍 Мне кажется, что ты не заметил несколько комментариев - ничего страшного, у нас будет время обсудить их в следующем спринте. Еще я оставил пару комментариев относительно того, как можно было бы улучшить твое хранилище. 🙌  Поздравляю с завершением первого спринта и завершением первого ревью! 🤗 Отличная работа! 🚀

2024-07-19 21:24 UTC, vokinneberg commented on internal/storage/inmemory.go
> +	mu sync.Mutex // синхронизация доступа к хранилищу
Здорово, что добавил синхронизацию. 👍  Подумай, как будет себя вести `sync.Mutex` в случае если запросы на чтение будут кратно превышать запросы на запись. Подсказка - мнжо посмотреть в сторону  `sync.RWMutex`.

2024-07-19 21:24 UTC, vokinneberg commented on internal/storage/base.go
> +type Storage interface {
👍 за реализацию интерфейса. Мне кажется нет необходимости объявлять интерфейс в отдельном файле. Попробуй объявить его там, где он используется.

2024-08-06 05:26 UTC, merged